- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Allow HTTP and HTTPS
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  notify:
    - Reload Firewalld

