- name: Install Apache
  apt:
    name: apache2
    state: present
  become: true

- name: Deploy Apache configuration
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/apache2.conf
  notify:
    - Restart Apache
  become: true

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: true
  become: true

